tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $THEIA_WORKSPACE_ROOT
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -f awscliv2.zip
#  - name: http-server
#    before: |
#      cd $THEIA_WORKSPACE_ROOT
#      npm install --global http-server
#    command: 
#      http-server
# aws cli for macos
      #curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
      #sudo installer -pkg AWSCLIV2.pkg -target /
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode